# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, "${{ matrix.os }}-${{ matrix.arch }}" ]
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        arch: [ amd64, arm64 ]

    steps:

      - name: Gather general system information
        run: |
          df -h
          uname -a
          free -mt

      - name: checkout v4
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Golang Environment v5
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '^1.21.6'

      - name: Go version
        run: go version

      - name: Get public IP information
        run: curl -sSf https://checkip.amazonaws.com

      - name: Docker s390x test
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -t --platform linux/s390x s390x/debian:stable-slim uname -a

      - name: jq test
        run: |
          echo '{"foo": 0}' | jq .

      - name: skopeo test
        run: |
          skopeo --version
          sudo ls -al /etc/containers
          sudo cat /etc/containers/policy.json
