name: Unit packaging checks workflow

on:
  workflow_call:

jobs:
  check-if-allowed:
    if: ${{ ( github.repository_owner == 'nginx' || github.repository_owner == 'nginxinc' ) }}
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Check if we're in the allowed environment
        run: |
          org_found=0
          event_found=0
          ref_found=0
          ALLOWED_ORGS="nginx nginxinc"
          ALLOWED_EVENTS="push"
          ALLOWED_REFS="refs/heads/main refs/heads/master"
          for org in $ALLOWED_ORGS; do
            if [ "$org" == "$GITHUB_REPOSITORY_OWNER" ]; then org_found=1; fi
          done
          for event in $ALLOWED_EVENTS; do
            if [ "$event" == "$GITHUB_EVENT_NAME" ]; then event_found=1; fi
          done
          for ref in $ALLOWED_REFS; do
            if [ "$ref" == "$GITHUB_REF" ]; then ref_found=1; fi
          done
          if [ $org_found$event_found$ref_found -ne 111 ]; then
            echo "Repository owner, event, or ref are not explicitely allowed to use this workflow: $GITHUB_REPOSITORY_OWNER, $GITHUB_EVENT_NAME, $GITHUB_REF"
            exit 1
          fi
          exit 0

  deb-packaging:
    runs-on: [ "${{ matrix.os }}-${{ matrix.arch }}" ]
    needs: check-if-allowed
    strategy:
      fail-fast: false
      matrix:
        os: [ debian-11, debian-12, ubuntu-20.04, ubuntu-22.04, ubuntu-23.10 ]
        arch: [ amd64, arm64 ]

    steps:
      - uses: actions/checkout@v4

      - name: deb packaging
        run: |
          cd pkg/deb
          make unit
          make modules

  rpm-packaging:
    runs-on: [ "${{ matrix.os }}-${{ matrix.arch }}" ]
    needs: check-if-allowed
    strategy:
      fail-fast: false
      matrix:
        os: [ amazonlinux-2, amazonlinux-2023, fedora38, fedora39, rhel-7, rhel-8, rhel-9 ]
        arch: [ amd64, arm64 ]
      exclude:
        - os: rhel-7 # AWS does not provide an RHEL 7 arm64 AMI
          arch: arm64
        - os: fedora-38
          arch: arm64
        - os: fedora-39
          arch: arm64

    steps:
      - name: checkout v3
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        if: ${{ matrix.os == 'amazonlinux-2' || matrix.os == 'rhel-7' }}

      - name: checkout v4
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: ${{ matrix.os != 'amazonlinux-2' && matrix.os != 'rhel-7' }}

      - name: rpm packaging
        run: |
          cd pkg/rpm
          make unit
          make modules
