name: Unit packaging checks workflow

on:
  workflow_call:

jobs:
  deb-packaging:
    if: ${{ ( github.repository_owner == 'nginx' || github.repository == 'nginxinc' ) }}
    runs-on: [ self-hosted, "${{ matrix.os }}-${{ matrix.arch }}" ]
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        arch: [ amd64 ]

    steps:
      - name: Check if we're in the allowed environment
        run: |
          org_found=0
          event_found=0
          ref_found=0
          ALLOWED_ORGS="nginx nginxinc"
          ALLOWED_EVENTS="push"
          ALLOWED_REFS="refs/heads/main refs/heads/master"
          for org in $ALLOWED_ORGS; do
            if [ "$org" == "$GITHUB_REPOSITORY_OWNER" ]; then org_found=1; fi
          done
          for event in $ALLOWED_EVENTS; do
            if [ "$event" == "$GITHUB_EVENT_NAME" ]; then event_found=1; fi
          done
          for ref in $ALLOWED_REFS; do
            if [ "$ref" == "$GITHUB_REF" ]; then ref_found=1; fi
          done
          if [ $org_found$event_found$ref_found -ne 111 ]; then
            echo "Repository owner, event, or ref are not explicitely allowed to use this workflow: $GITHUB_REPOSITORY_OWNER, $GITHUB_EVENT_NAME, $GITHUB_REF"
            exit 0
          fi

      - name: dump the environment
        run: |
          env

      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
